# Generated by Django 3.0.3 on 2020-02-11 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todos_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='author',
        ),
        migrations.RemoveField(
            model_name='todos',
            name='nationality',
        ),
        migrations.AddField(
            model_name='todos',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='todos',
            name='text',
            field=models.CharField(default='default', max_length=500),
        ),
        migrations.AlterField(
            model_name='todos',
            name='title',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
