# Generated by Django 3.0.3 on 2020-02-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200211_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='title',
        ),
        migrations.AddField(
            model_name='todos',
            name='when',
            field=models.CharField(default='default', max_length=500),
        ),
        migrations.AlterField(
            model_name='todos',
            name='text',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
