# Generated by Django 3.0.3 on 2020-02-12 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20200211_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='text',
        ),
        migrations.AddField(
            model_name='todos',
            name='proj_desc',
            field=models.CharField(default='Project Description', max_length=100),
        ),
        migrations.AlterField(
            model_name='todos',
            name='when',
            field=models.CharField(default='Time of Day', max_length=500),
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Add your name', max_length=100)),
                ('comment', models.TextField()),
                ('message', models.TextField()),
                ('todos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='todo.Todos')),
            ],
        ),
    ]
