# Generated by Django 3.0.3 on 2020-02-12 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20200212_1643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todos',
            new_name='Todo',
        ),
        migrations.RemoveField(
            model_name='list',
            name='todos',
        ),
        migrations.AddField(
            model_name='list',
            name='todo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todo.Todo'),
            preserve_default=False,
        ),
    ]
